require('nvPlugins.packerPlugins')
require('nvPlugins.lspinstaller')
require('nvPlugins.telescope')
require('nvPlugins.shade')
require('nvPlugins.spellsitter')
require('nvPlugins.tabline')
require('nvPlugins.statusline')
