
-- require'lspconfig'.texlab.setup{
--   cmd = { 'texlab' },
--   filetypes = { 'tex', 'bib' },
--   settings = {
--     texlab = {
--       auxDirectory = '.',
--       bibtexFormatter = 'texlab',
--       build = {
--         executable = 'latexmk',
--         args = { '-pdf', '-outdir=build', '-interaction=nonstopmode', '-synctex=0', '%f' },
--         forwardSearchAfter = false,
--         onSave = true,
--       },
--       chktex = {
--         onEdit = true,
--         onOpenAndSave = false,
--       },
--       diagnosticsDelay = 300,
--       formatterLineLength = 80,
--       forwardSearch = {
-- 				executable = 'zathura',
--         args = { '%p' }
--       },
--       latexFormatter = 'latexindent',
--       latexindent = {
--         modifyLineBreaks = false,
--       }
--     }
--   }
-- }
-- vim.g.vimtex_compiler_method = "latexmk"
-- vim.g.vimtex_view_method = "zathura"
-- vim.g.vimtex_fold_enabled = 0


-- Compile on initialization, cleanup on quit
-- vim.api.nvim_exec(
--   [[
--         augroup vimtex_event_1
--             au!
--             au User VimtexEventQuit     call vimtex#compiler#clean(0)
--             au User VimtexEventInitPost call vimtex#compiler#compile()
--         augroup END
--     ]],
--   false
-- )
